feat: Add April's fact
octopusthink/funfactsaboutoctopus.es pull request #21
Opened 2020-04-09 13:58 UTC by sarahmonster

Let's get facting again!

This also introduces some very small changes to the visual design, mostly to account for Nautilus' updated Link component. I think it looks sharper:

![image](https://user-images.githubusercontent.com/376315/78903031-82f24f80-7a72-11ea-88a3-2cd831568773.png)

I had some weirdness whilst trying to update Nautilus, so I'm unclear on whether it worked or not—I got a bunch of errors, and then I had to roll back changes to my package.json in order to get the site to build. 

If the links don't match the above screenshot, something went wrong and we may need to bugfix.

2020-04-09 22:34 UTC, tofumatt requested changes
I have some thoughts on the copy text—let me know what you think.

2020-04-09 22:34 UTC, tofumatt commented on src/content/facts/12-de-montfort.md
> +Pierre Denys de Montfort was a French naturalist who had something of an obsession with giant octopuses. And you know how, when you think about something a whole lot, you start seeing it everywhere?
On first pass this sentence read a bit awkwardly to me. Here's my suggestion to tighten it up a little:

```suggestion
Pierre Denys de Montfort was a French naturalist who had something of an obsession with giant octopuses. You know how thinking about something a lot, you start seeing it everywhere? Yup, that's what happened here.
```

2020-04-09 22:34 UTC, tofumatt commented on src/content/facts/12-de-montfort.md
> +de Montfort told everyone they'd sunk a group of warships that mysteriously disappeared one night in 1782. Turns out the disappearance was less of a mystery than originally proposed and he was summar
"They'd" is _quite_ an ambiguous noun here—I thought it meant that de Montfort told people that the people had sunk a warship. How about we clarify:

```suggestion
One night in 1782, when a group of warships mysteriously disappeared, de Montfort claimed it was the work of giant octopuses. Turns out the disappearances weren't a mystery, but were a secret kept by the British Navy. After this revelation, de Montfort's career tanked (probably attacked by a giant octopus).
```

2020-04-09 22:35 UTC, tofumatt commented
(Love the image, by the way.)

2020-04-09 23:04 UTC, tofumatt commented
(This wasn't building for me locally but an update to the dependencies got things working for me.)

2020-04-10 14:08 UTC, sarahmonster commented
Okay! I started with your copyedits, and then they got more copyedity as I kept going. I've also updated Nautilus to pick up recent changes to links, and I've fleshed out the README a wee bit. 

Let me know what you think!

2020-04-10 14:10 UTC, tofumatt approved these changes

2020-04-10 14:10 UTC, merged